### ISSUE TITLE
What about having separate branches for different jdk versions?

### ISSUE THREAD

**Issue by ryenus** [rwinch/gradle-multi-jdk#1]

**Comment by rwinch** [comment]
I'm not sure I understand the comment. If you were using separate branches, then you would not need any Gradle magic.

This project was really meant to help me remember how to build a single source with multiple JDKs. This is often times important for frameworks that want to ensure that a single source works across multiple JDKs.

**Comment by ryenus** [comment]
@rwinch, I mean the deploy to maven central part of the story, in Maven we need to use classifiers for different Java versions, I wonder how this is handled.

Thank you!
